### PR TITLE
Feat: immerJS for flows-133

### PR DESCRIPTION
**Pull request by BastinJafari**

### CODE REVIEW

**Comment by BastinJafari** [comment]
There are issues because of the fact that two states exist. One in the flow library and one in redux. I would wait for this PR until we have a new flow library

**Review by Roshanjossey — APPROVED** [review]

**Comment by DavidSanwald** [comment]
Hey just wanted to congratulate you for choosing immerjs. 
Personally, I can relate why, especially ambitious and bright devs feel drawn to ImmutableJS or alternatives (I like https://github.com/swannodette/mori but I'm a sucker for everything Clojure).
I think immer isn't particularly exciting but it might be the most pragmatic and future-proof solution, which is best for the project.
I'm happy to see that the dashboard thrives and is moving in a good direction.
Congratulation to the whole team.

**Comment by DavidSanwald** [comment]
It's a good PR and there was obviously a lot of work, that went into it.
So don't let it become stale. Just `run: ` something like that       ` echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` to increase the number of watchers.

**Comment by BastinJafari** [comment]
Thanks a lot for the feedback David!
I Will look into the stuff you recommended, thank you also for that :D

I didn't merge this PR, because I am implementing it into the change of the flow chart library. 
We will use https://reactflow.dev/

**Pull request closed without merging**
