### PR TITLE
feat: test server/recorder

### PR DESCRIPTION
**Pull request by imsergiy**
The test server has two functions:
1. Record jina flows
2. Simulate jina flows

### Recording Flows
To record, start a Jina flow and make sure the logserver is enabled. The recorder will connect to the corresponding `url` and store the data received from `yaml`, `profile`, and `log` endpoints as defined in `config.js`. To end the recording, type `ctrl+c` and the recorder will generate a JSON file with the data of the session.

To start recording, run:
```bash
node testserver --record
```

You can override config and point to a specific URL using:
```bash
node testserver --record=<CUSTOM_URL>
```

### Simulating Flows
Once you have a valid recorded flow, you can play it back via SSE. A local server is started and transmission begins when a request arrives. Events are scheduled for transmission by their `received` property to simulate order and frequency.

To start a flow simulation, run:
```bash
node testserver
```
You can override config and specify a source by using:
```bash
node testserver --source=<PATH_TO_SOURCE>
```
To specify a port:
```bash
node testserver --port=<PORT_NUMBER>
```

### Other Changes
- `testServer.js` => `testserver.js`
- organize `dev-resources/` directory
- add initial `examples/hello-world.json` recording
- add `stream/profile` to emitter
- formatted console output, status updates

### CODE REVIEW

**Review by DavidSanwald — APPROVED** [review]
Just skimmed through it on the surface for three reasons:
- I'm to a backend dev and I feel like this is something close to your preferences and experience
- It's the testServer. It will be very helpful and is important for us but it's not able to create any instability or problems in the rest of the codebase most importantly in the dashboard.
- I already asked you, if you could give me a tour and explain some or your thinking and the general process that lead to this solution on a call and you were kind enough to agree on this (: 

That said I read through all the code once and made sure it's not launching any missiles somewhere. Looking forward to test (or rather use) it (:

**Comment by DavidSanwald** [comment]
I know I was the one that brought up "recording" idea.
And it's really cool to have it now.
Maybe assuming that the timestamps of the logs are a good enough estimate of the time they arrive/are reviewed by the backend would have simplified things so we wouldn't need to actually record how the logs are actually received. 
But I actually don't know at all if the timestamps of the logs are a good enough approximation of how they arrive at the backend. So it's cool that we can record and I'd love to compare the recordings with the timestamps from when an event was logged.
One question it's maybe easier to ask than digging into the code:
Would it be possible to play some logs, that aren't recorded by the testServer and only dumped to a file from some run using just the timestamps of the logs for scheduling? That would add even more value to everything.

**Comment by imsergiy** [comment]
Initially, I had it send stream items based on `<item>.created` and calculated a delay from the very first item. What I found though was that running a flow such as `hello-world` would create a bunch of `task` items, but they would not be sent out until later, all at once. To see this, compare the `created` property of the first `log` item and first `profile` item in `examples/hello-world.json`, what you will find is a difference of 44 seconds which of course is not how they actually arrive when you connect the dashboard directly to the flow. Using the `created` property of a stream item is unfortunately not a good indication of how/when events are actually sent out and able to be received and it's important to capture this frequency in our simulations.

It would certainly be possible to play back from a file, provided they are formatted in JSON (not a console pipe to a text file). We can use the `created` property in this case to schedule events. There are 2 other key data sources: `profile` and `flow` that ideally should also somehow be provided by this file.

**Comment by DavidSanwald** [comment]
> Initially, I had it send stream items based on `<item>.created` and calculated a delay from the very first item. What I found though was that running a flow such as `hello-world` would create a bunch of `task` items, but they would not be sent out until later, all at once. To see this, compare the `created` property of the first `log` item and first `profile` item in `examples/hello-world.json`, what you will find is a difference of 44 seconds which of course is not how they actually arrive when you connect the dashboard directly to the flow. Using the `created` property of a stream item is unfortunately not a good indication of how/when events are actually sent out and able to be received and it's important to capture this frequency in our simulations.
> 
> It would certainly be possible to play back from a file, provided they are formatted in JSON (not a console pipe to a text file). We can use the `created` property in this case to schedule events. There are 2 other key data sources: `profile` and `flow` that ideally should also somehow be provided by this file.

Yeah, that's why I wasn't so sure about just using the time stamps.
Very good to have the recording capability now. It's also interesting because I feel like seeing the delay/offset between when a log is created and when it's arriving could be helpful. I would assume that there's a huge spectrum from almost no delay to the behaviour you described when logs are batched.

**Pull request merged**
