### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by Roshanjossey**
Currently, contribution guidelines in dashboard refers to CONTRIBUTING.md in jina. 

It makes sense to have contribution guidelines specifically for this repository.

### CODE REVIEW

**Review by BastinJafari — APPROVED** [review]
It's basically the same as for the core, right?
So I see no issue to merge it

**Comment by alexcg1** [comment]
Yeah - we should just redirect everyone to core code of conduct. Otherwise we're looking at more maintenance

**Comment by Roshanjossey** [comment]
@BastinJafari, the only difference is how to run console locally and how to run tests. Also, I've used `console` rather than `dashboard` to refer to this project. We should also consider if we should start with the change in nomenclature now.

**Comment by Roshanjossey** [comment]
@alexcg1, were you referring to the other pull request about adding code of conduct?

**Comment by alexcg1** [comment]
> @alexcg1, were you referring to the other pull request about adding code of conduct?

Ha, yes. I got confused

**Pull request merged**
