### PR TITLE
Add integration tests for log view

### PR DESCRIPTION
**Pull request by ravishankarste**

### CODE REVIEW

**Comment by BastinJafari** [comment]
Thank you very much for your PR @ravishankarste 
We have changed the Design of flowView, so it doesn't contain a dropdown anymore and also use data-* attributes.

https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements

Feel invited to add additional tests to the existing ones!

**Comment by BastinJafari** [comment]
Hey Ravi, thanks for the changes!
I checked out your branch and the tests were failing (`npm run cy:run `or `npm run cy:dev`).
You are referencing attributes that don't exist in the code like "dropDown-3-ViewSelectedOption"

**Comment by ravishankarste** [comment]
Hey Bastin

I expected that to happen because I made some changes in dev code but i
didn't push.. I asked josh if I can push that as well... If it's ok i will
push those changes as well.

**Comment by BastinJafari** [comment]
That would be nice. Also checkout the newest version.
I added a test for checking the correct logging output:

image


Maybe you could add to that and check if it is also correct for all the dropdown categories

**Comment by ravishankarste** [comment]
Thanks, I'll check it out.

**Comment by Roshanjossey** [comment]
Closing this in favour of #277

**Pull request closed without merging**
